using System.ComponentModel.DataAnnotations;

namespace AssetHub.Api.Entities.Assets;

public class AssetInputDto
{
    public int Id { get; set; }
    // Code is server-owned (generated by AssetCodePrimer) -- omitted here on purpose.
    [Required, MaxLength(150)]
    public string Title { get; set; } = null!;
    [MaxLength(1000)]
    public string? Description { get; set; }
    [MaxLength(100)]
    public string? SerialNumber { get; set; }

    [Required]
    public int CategoryId { get; set; }
    [Required]
    public int StatusId { get; set; }
    public int? LocationId { get; set; }
    public int? SupplierId { get; set; }

    public DateTime? PurchaseDate { get; set; }
    public decimal? PurchasePrice { get; set; }
    [MaxLength(1000)]
    public string? Notes { get; set; }

    // Keep on the DTO -- excluding it would make restoring an archived asset impossible.
    public bool IsArchived { get; set; }

    // Nullable + uninitialized: null = untouched, [] = delete-all (Related() contract).
    public ICollection<AssetAttachmentInputDto>? Attachments { get; set; }
    public ICollection<AssetWarrantyInputDto>? Warranties { get; set; }
    public ICollection<AssetMaintenanceRecordInputDto>? MaintenanceRecords { get; set; }
}
