<template>
    <form @submit.prevent="handleSubmit">
        <div class="row form-toolbar align-items-center mb-2">
            <div class="col col-md-auto order-1">
                <FormButtonsRow
                    :item="item"
                    :readonly="readonly"
                    :feedback="feedback"
                    :show-delete="item?.id > 0"
                    :labels="{ save: $t('save'), cancel: $t('cancel'), delete: $t('delete'), restore: $t('restore') }"
                    :modal-title="$t('delete')"
                    @cancel="handleCancel"
                    @remove="handleRemove"
                    @restore="handleRestore"
                >
                    <template #delete>{{ $t("deleteItem", { title: item?.$title }) }}</template>
                </FormButtonsRow>
            </div>
            <div class="col-auto order-2 order-md-3">
                <RouterLink
                    v-if="isPopup"
                    :to="{ name: `${config.key}Details`, params: { id: item.$id } }"
                    target="_blank"
                    class="btn btn-outline-secondary"
                    :title="$t('popOut')"
                >
                    <Icon name="popOut" />
                </RouterLink>
                <RouterLink v-else-if="overviewUrl" :to="overviewUrl" class="btn btn-outline-info">
                    <Icon name="list" /> <span class="d-none d-md-inline ms-1">{{ $t("overview") }}</span>
                </RouterLink>
            </div>
            <div class="col-md order-3 order-md-2"><Feedback :feedback="feedback" /></div>
        </div>

        <!-- asset header card -->
        <div v-if="item.id > 0" class="ah-asset-head mb-3" :style="{ '--ah-status-color': status?.color || '#6c757d' }">
            <div class="ah-card__icon ah-card__icon--lg"><i :class="category?.$iconClass || 'bi bi-box'"></i></div>
            <div class="flex-grow-1 min-w-0">
                <div class="fs-5 fw-semibold text-truncate">{{ item.title }}</div>
                <div class="small text-muted text-truncate">
                    <span class="ah-code">{{ item.code }}</span>
                    <span v-if="item.serialNumber"> &middot; SN {{ item.serialNumber }}</span>
                    <span v-if="category"> &middot; {{ category.$title }}</span>
                </div>
            </div>
            <div class="text-end">
                <StatusBadge :status="status" />
                <div v-if="item.currentEmployee" class="small mt-1 text-truncate">
                    <Icon name="user" /> {{ holder?.$title }}
                </div>
            </div>
        </div>

        <TabContainer :tabs="tabs" :active="initialTab" :use-route-nav="!isPopup">
            <template #form>
                <FormSection :title="$t('general')" :readonly="readonly">
                    <div class="row">
                        <div class="col-md-3 mb-3">
                            <div class="input-group">
                                <span class="input-group-text"><Icon name="tag" /></span>
                                <input v-model.trim="item.code" maxlength="16" :readonly="readonly" class="form-control text-uppercase" :placeholder="$t('autoGenerated')" />
                            </div>
                            <FormLabel :label="$t('assetTag')" />
                        </div>
                        <div class="col-md-9 mb-3">
                            <div class="input-group">
                                <span class="input-group-text"><Icon name="title" /></span>
                                <input v-model="item.title" required maxlength="128" :readonly="readonly" class="form-control" />
                            </div>
                            <FormLabel :label="$t('name')" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <CategorySelector v-model="item.category" v-model:idValue="item.categoryId as number" :readonly="readonly" :placeholder="$t('category')" />
                            <FormLabel :label="$t('category')" />
                        </div>
                        <div class="col-md-6 mb-3">
                            <AssetStatusSelector v-model="item.status" v-model:idValue="item.statusId as number" :readonly="readonly" :placeholder="$t('status')" />
                            <FormLabel :label="$t('status')" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 mb-3">
                            <input v-model="item.manufacturer" maxlength="64" :readonly="readonly" class="form-control" />
                            <FormLabel :label="$t('manufacturer')" />
                        </div>
                        <div class="col-md-4 mb-3">
                            <input v-model="item.model" maxlength="64" :readonly="readonly" class="form-control" />
                            <FormLabel :label="$t('model')" />
                        </div>
                        <div class="col-md-4 mb-3">
                            <div class="input-group">
                                <span class="input-group-text"><Icon name="code" /></span>
                                <input v-model.trim="item.serialNumber" maxlength="64" :readonly="readonly" class="form-control" />
                            </div>
                            <FormLabel :label="$t('serialNumber')" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <LocationSelector v-model="item.location" v-model:idValue="item.locationId as number" :readonly="readonly" :placeholder="$t('location')" />
                            <FormLabel :label="$t('location')" />
                        </div>
                        <div class="col-md-6 mb-3">
                            <textarea v-model="item.description" rows="2" maxlength="2048" :readonly="readonly" class="form-control"></textarea>
                            <FormLabel :label="$t('description')" />
                        </div>
                    </div>
                </FormSection>
                <FormSection :title="$t('purchase')" :readonly="readonly">
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <SupplierSelector v-model="item.supplier" v-model:idValue="item.supplierId as number" :readonly="readonly" :placeholder="$t('supplier')" />
                            <FormLabel :label="$t('supplier')" />
                        </div>
                        <div class="col-md-2 mb-3">
                            <input v-model="item.purchaseDate" type="date" :readonly="readonly" class="form-control" />
                            <FormLabel :label="$t('purchaseDate')" />
                        </div>
                        <div class="col-md-2 mb-3">
                            <div class="input-group">
                                <span class="input-group-text"><Icon name="euro" /></span>
                                <input v-model.number="item.purchasePrice" type="number" min="0" step="0.01" :readonly="readonly" class="form-control" />
                            </div>
                            <FormLabel :label="$t('price')" />
                        </div>
                        <div class="col-md-2 mb-3">
                            <input v-model.trim="item.orderNumber" maxlength="32" :readonly="readonly" class="form-control" />
                            <FormLabel :label="$t('orderNumber')" />
                        </div>
                    </div>
                </FormSection>
            </template>

            <template #assignment>
                <AssignmentPanel :item="item" :readonly="readonly" @changed="applyWorkflowResult" />
            </template>

            <template #warranties>
                <FormSection :title="$t('warranties')">
                    <WarrantyOverview v-model="item.warranties" :readonly="readonly" />
                </FormSection>
            </template>

            <template #maintenance>
                <FormSection :title="$t('maintenance')">
                    <MaintenanceRecordOverview v-model="item.maintenanceRecords" :readonly="readonly" />
                </FormSection>
            </template>

            <template #files>
                <EntityAttachments v-model="item.attachments" :readonly="readonly" />
            </template>
        </TabContainer>

        <Debug :modelValue="{ item }" />
    </form>
</template>

<script setup lang="ts">
import { computed } from "vue"
import { RouterLink, type RouteRecordRaw } from "vue-router"
import { Feedback, FormButtonsRow, FormSection, FormLabel, Icon, TabContainer, Tab } from "@regira/modules/vue/ui"
import { Debug } from "@regira/modules/vue/debug"
import { useLang } from "@regira/modules/vue/lang"
import { useForm, type FormEmits, formDefaults } from "@regira/modules/vue/entities"
import StatusBadge from "@/components/StatusBadge.vue"
import { InputSelector as CategorySelector, useEntityStore as useCategoryStore } from "@/entities/categories"
import { InputSelector as AssetStatusSelector, useEntityStore as useAssetStatusStore } from "@/entities/asset-statuses"
import { InputSelector as LocationSelector } from "@/entities/locations"
import { InputSelector as SupplierSelector } from "@/entities/suppliers"
import { useEntityStore as useEmployeeStore } from "@/entities/employees"
import { Overview as EntityAttachments } from "../../entity-attachments"
import { WarrantyOverview } from "../warranties"
import { MaintenanceRecordOverview } from "../maintenance-records"
import config from "../config/config"
import Entity from "../data/Entity"
import useEntityStore from "../data/store"
import AssignmentPanel from "./AssignmentPanel.vue"

interface Emits extends /* @vue-ignore */ FormEmits<Entity> {}
const emit = defineEmits<Emits>()
const props = withDefaults(
    defineProps<{ modelValue: Entity; readonly?: boolean; overviewUrl?: string | RouteRecordRaw; isPopup?: boolean; initialTab?: string }>(),
    { ...formDefaults }
)

const { service: entityService } = useEntityStore()
const { item, feedback, handleCancel, handleSubmit, handleRemove, handleRestore } = useForm<Entity>({ entityService, props, emit })

const { fromPool: getCategory } = useCategoryStore()
const { fromPool: getAssetStatus } = useAssetStatusStore()
const { fromPool: getEmployee } = useEmployeeStore()
const category = computed(() => (item.value?.category ? getCategory(item.value.category) : undefined))
const status = computed(() => (item.value?.status ? getAssetStatus(item.value.status) : undefined))
const holder = computed(() => (item.value?.currentEmployee ? getEmployee(item.value.currentEmployee) : undefined))

// The assign / return actions answer with a re-read; land only the workflow-owned fields so pending form edits survive.
function applyWorkflowResult(fresh: Entity) {
    const target = item.value
    target.currentEmployeeId = fresh.currentEmployeeId
    target.currentEmployee = fresh.currentEmployee
    target.assignedOn = fresh.assignedOn
    target.assignments = fresh.assignments
    target.statusId = fresh.statusId
    target.status = fresh.status
    target.lastModified = fresh.lastModified
}

const { translate } = useLang()
const tabs = computed(() => {
    const isNew = !item.value?.id
    const count = (arr?: Array<{ _deleted?: boolean } | object>) => (arr?.filter((x) => !(x as { _deleted?: boolean })._deleted).length ? ` (${arr.filter((x) => !(x as { _deleted?: boolean })._deleted).length})` : "")
    return [
        Tab.create("form", { icon: "form", title: translate("details"), isDefault: true }),
        Tab.create("assignment", { icon: "user", title: translate("assignment") + count(item.value?.assignments), isDisabled: isNew }),
        Tab.create("warranties", { icon: "security", title: translate("warranties") + count(item.value?.warranties) }),
        Tab.create("maintenance", { icon: "wrench", title: translate("maintenance") + count(item.value?.maintenanceRecords) }),
        Tab.create("files", { icon: "attachment", title: translate("files") + count(item.value?.attachments) }),
    ]
})
</script>
